repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        exclude: (sessions/2-serial/2-simd/*|solution-proposal)
        stages: [commit]
        language: system
        entry: jupyter-nbconvert --ClearOutputPreprocessor.enabled=True --inplace

