name: deploy-book

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  meta:
    runs-on: self-hosted
    outputs:
      tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy-book:
    needs: meta
    runs-on: self-hosted
    container:
      image: ghcr.io/robertrosca/julia-hpc-workshop:${{ needs.meta.outputs.tag }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ./_build/.jupyter_cache

    - name: Setup
      run: |
        echo $JULIA_DEPOT_PATH
        make setup
        julia -e "using Pkg; Pkg.status()"
        julia --project=@. -e "using Pkg; Pkg.status()"

    - name: Build the book
      run: |
        export JULIA_PROJECT=$PWD
        make html

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
        destination_dir: ./${{ needs.meta.outputs.tag }}
